### PR TITLE
Fixing Prowlarr via VPN

### PR DESCRIPTION
**Pull request by RobinFlikkema**
This is a fix for the error mentioned on commit bf1cd779310ff4e119a1a4e1b6c4a1b793e501ce

Error response from daemon: conflicting options: port publishing and the container type network mode

### CODE REVIEW

**Comment by RobinFlikkema** [comment]
Excuse me if I'm overlooking something. But this fix seems to work.

I  commented the ports out so people could use that when not using VPN. But I'm unsure if this is the way to go since I'm only running profile 2.

@bakersomo, this should fix your issue also since this is the fix you mentioned :)

**Comment by wdfrench13** [comment]
I got the gluetun container/mullvad VPN/prowlarr setup working this weekend using this PR and info from the link you shared, @RobinFlikkema 

One key bit that took me a bit to find: you need to add an outbound firewall rule to the gluetun container to talk to the secondary docker network, like so: - FIREWALL_OUTBOUND_SUBNETS=172.18.0.0/24 as shown in [this answer ](https://github.com/qdm12/gluetun/issues/281#issuecomment-958107966)

Your work here was very helpful, thanks!

**Comment by navilg** [comment]
Thanks @RobinFlikkema I surely missed to add those ports in main branch.

**Comment by navilg** [comment]
> One key bit that took me a bit to find: you need to add an outbound firewall rule to the gluetun container to talk to the secondary docker network, like so: - FIREWALL_OUTBOUND_SUBNETS=172.18.0.0/24 as shown in [this answer ](https://github.com/qdm12/gluetun/issues/281#issuecomment-958107966)
> 
is it required when VPN container is running in different network than other stacks? I am not sure about this issue. Here we have considered all the containers (including vpn) in same network.

**Comment by RobinFlikkema** [comment]
> I got the gluetun container/mullvad VPN/prowlarr setup working this weekend using this PR and info from the link you shared, @RobinFlikkema
> 
> One key bit that took me a bit to find: you need to add an outbound firewall rule to the gluetun container to talk to the secondary docker network, like so: - FIREWALL_OUTBOUND_SUBNETS=172.18.0.0/24 as shown in [this answer ](https://github.com/qdm12/gluetun/issues/281#issuecomment-958107966)
> 
> Your work here was very helpful, thanks!

Unsure. I just assigned static IPs to the containers and then it all seems to work.

**Pull request merged**
